[2024-06-01 19:13:57,674 - INFO - main: Welcome to our custom log]
[2024-06-01 19:51:43,673 - INFO - main: Welcome to our custom log]
[2024-06-03 13:17:53,020 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-03 13:17:53,041 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-03 13:17:53,043 - INFO - common: created directory at: artifacts]
[2024-06-03 13:17:53,046 - INFO - common: created directory at: artifacts/data_ingestion]
[2024-06-03 13:26:12,137 - INFO - 770202532: artifacts/data_ingestion/data.zip downloaded with the following info: 
Connection: close
Content-Length: 7903594
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "dbc016a060da18070593b83afff580c9b300f0b6ea4147a7988433e04df246ca"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 5348:234927:CA2B3:E6BDE:665D6017
Accept-Ranges: bytes
Date: Mon, 03 Jun 2024 06:18:00 GMT
Via: 1.1 varnish
X-Served-By: cache-lax-kwhp1940131-LAX
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1717395480.808698,VS0,VE734
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 9eb87c2dae0accaa33af3a9387917f5ba93b65f1
Expires: Mon, 03 Jun 2024 06:23:00 GMT
Source-Age: 1

]
[2024-06-03 14:11:23,440 - INFO - main: >>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-03 14:11:23,442 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-03 14:11:23,443 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-03 14:11:23,444 - INFO - common: created directory at: artifacts]
[2024-06-03 14:11:23,444 - INFO - common: created directory at: artifacts/data_ingestion]
[2024-06-03 14:26:10,645 - INFO - data_ingestion: artifacts/data_ingestion/data.zip downloaded with the following info: 
Connection: close
Content-Length: 7903594
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "dbc016a060da18070593b83afff580c9b300f0b6ea4147a7988433e04df246ca"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 5348:234927:CA2B3:E6BDE:665D6017
Accept-Ranges: bytes
Date: Mon, 03 Jun 2024 07:11:27 GMT
Via: 1.1 varnish
X-Served-By: cache-lax-kwhp1940078-LAX
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1717398687.010918,VS0,VE110
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 6f94e7d2eacd6e076ba80d03ddc932013d4e624e
Expires: Mon, 03 Jun 2024 07:16:27 GMT
Source-Age: 0

]
[2024-06-03 14:26:10,812 - INFO - main: >>>>> stage Data Ingestion stage completed <<<<<<

x=========x]
[2024-06-05 19:07:25,145 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-05 19:07:25,160 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-05 19:07:25,162 - INFO - common: created directory at: artifacts]
[2024-06-05 19:07:25,165 - INFO - common: created directory at: artifacts/data_validation]
[2024-06-05 19:08:48,579 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-05 19:08:48,582 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-05 19:08:48,583 - INFO - common: created directory at: artifacts]
[2024-06-05 19:08:48,585 - INFO - common: created directory at: artifacts/data_validation]
[2024-06-05 19:09:54,296 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-05 19:09:54,299 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-05 19:09:54,300 - INFO - common: created directory at: artifacts]
[2024-06-05 19:09:54,302 - INFO - common: created directory at: artifacts/data_validation]
[2024-06-05 19:11:53,783 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-05 19:11:53,787 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-05 19:11:53,788 - INFO - common: created directory at: artifacts]
[2024-06-05 19:11:53,790 - INFO - common: created directory at: artifacts/data_validation]
[2024-06-05 19:13:43,473 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-05 19:13:43,475 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-05 19:13:43,478 - INFO - common: created directory at: artifacts]
[2024-06-05 19:13:43,480 - INFO - common: created directory at: artifacts/data_validation]
[2024-06-05 19:14:35,415 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-05 19:14:35,417 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-05 19:14:35,419 - INFO - common: created directory at: artifacts]
[2024-06-05 19:14:35,421 - INFO - common: created directory at: artifacts/data_validation]
[2024-06-05 19:23:07,058 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-05 19:23:07,060 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-05 19:23:07,062 - INFO - common: created directory at: artifacts]
[2024-06-05 19:23:07,064 - INFO - common: created directory at: artifacts/data_validation]
[2024-06-05 20:32:55,009 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-05 20:32:55,018 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-05 20:32:55,022 - INFO - common: created directory at: artifacts]
[2024-06-05 20:32:55,026 - INFO - common: created directory at: artifacts/data_validation]
[2024-06-05 20:37:33,065 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-05 20:37:33,069 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-05 20:37:33,071 - INFO - common: created directory at: artifacts]
[2024-06-05 20:37:33,074 - INFO - common: created directory at: artifacts/data_validation]
[2024-06-05 20:43:08,766 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-05 20:43:08,771 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-05 20:43:08,774 - INFO - common: created directory at: artifacts]
[2024-06-05 20:43:08,777 - INFO - common: created directory at: artifacts/data_validation]
[2024-06-05 20:49:39,318 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-05 20:49:39,323 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-05 20:49:39,326 - INFO - common: created directory at: artifacts]
[2024-06-05 20:49:39,330 - INFO - common: created directory at: artifacts/data_validation]
[2024-06-05 20:56:50,211 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-05 20:56:50,217 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-05 20:56:50,221 - INFO - common: created directory at: artifacts]
[2024-06-05 20:56:50,223 - INFO - common: created directory at: artifacts/data_validation]
[2024-06-05 20:57:11,448 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-05 20:57:11,451 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-05 20:57:11,453 - INFO - common: created directory at: artifacts]
[2024-06-05 20:57:11,457 - INFO - common: created directory at: artifacts/data_validation]
[2024-06-05 20:58:49,789 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-05 20:58:49,791 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-05 20:58:49,793 - INFO - common: created directory at: artifacts]
[2024-06-05 20:58:49,794 - INFO - common: created directory at: artifacts/data_validation]
[2024-06-05 21:02:44,167 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-05 21:02:44,170 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-05 21:02:44,172 - INFO - common: created directory at: artifacts]
[2024-06-05 21:02:44,174 - INFO - common: created directory at: artifacts/data_validation]
[2024-06-05 21:15:43,642 - INFO - main: >>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-05 21:15:43,645 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-05 21:15:43,645 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-05 21:15:43,646 - INFO - common: created directory at: artifacts]
[2024-06-05 21:15:43,646 - INFO - common: created directory at: artifacts/data_ingestion]
[2024-06-05 21:15:43,647 - ERROR - main: 'DataIngestion' object has no attribute 'get_size']
Traceback (most recent call last):
  File "c:\Users\USER\Documents\Text-Summarizer-NLP-Project\main.py", line 9, in <module>
    data_ingestion.main()
  File "c:\Users\USER\Documents\Text-Summarizer-NLP-Project\src\textSummarizer\pipeline\stage_01_data_ingestion.py", line 13, in main
    data_ingestion.download_file()
  File "C:\Users\USER\Documents\Text-Summarizer-NLP-Project\src\textSummarizer\components\data_ingestion.py", line 21, in download_file
    logger.info(f"File already exists of size: {self.get_size(Path(self.config.local_data_file))}")
                                                ^^^^^^^^^^^^^
AttributeError: 'DataIngestion' object has no attribute 'get_size'
[2024-06-05 21:15:59,295 - INFO - main: >>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-05 21:15:59,298 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-05 21:15:59,299 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-05 21:15:59,299 - INFO - common: created directory at: artifacts]
[2024-06-05 21:15:59,300 - INFO - common: created directory at: artifacts/data_ingestion]
[2024-06-05 21:16:13,062 - INFO - data_ingestion: artifacts/data_ingestion/data.zip downloaded with the following info: 
Connection: close
Content-Length: 7903594
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "dbc016a060da18070593b83afff580c9b300f0b6ea4147a7988433e04df246ca"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: C710:1507FC:1DACED:2352CC:66607328
Accept-Ranges: bytes
Date: Wed, 05 Jun 2024 14:16:09 GMT
Via: 1.1 varnish
X-Served-By: cache-qpg1232-QPG
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1717596969.701308,VS0,VE681
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 9c29903c6834382c75212e3239960a7cd1f977eb
Expires: Wed, 05 Jun 2024 14:21:09 GMT
Source-Age: 0

]
[2024-06-05 21:16:13,230 - INFO - main: >>>>> stage Data Ingestion stage completed <<<<<<

x=========x]
[2024-06-05 21:16:13,231 - INFO - main: >>>>> stage Data validation stage started <<<<<<]
[2024-06-05 21:16:13,233 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-05 21:16:13,234 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-05 21:16:13,235 - INFO - common: created directory at: artifacts]
[2024-06-05 21:16:13,236 - INFO - common: created directory at: artifacts/data_ingestion]
[2024-06-05 21:16:13,236 - ERROR - main: 'DataValidation' object has no attribute 'download_file']
Traceback (most recent call last):
  File "c:\Users\USER\Documents\Text-Summarizer-NLP-Project\main.py", line 19, in <module>
    data_validation.main()
  File "c:\Users\USER\Documents\Text-Summarizer-NLP-Project\src\textSummarizer\pipeline\stage_02_data_validation.py", line 13, in main
    data_validation.download_file()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataValidation' object has no attribute 'download_file'
[2024-06-05 21:19:22,097 - INFO - main: >>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-05 21:19:22,100 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-05 21:19:22,100 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-05 21:19:22,102 - INFO - common: created directory at: artifacts]
[2024-06-05 21:19:22,102 - INFO - common: created directory at: artifacts/data_ingestion]
[2024-06-05 21:19:22,102 - ERROR - main: 'DataIngestion' object has no attribute 'get_size']
Traceback (most recent call last):
  File "c:\Users\USER\Documents\Text-Summarizer-NLP-Project\main.py", line 9, in <module>
    data_ingestion.main()
  File "c:\Users\USER\Documents\Text-Summarizer-NLP-Project\src\textSummarizer\pipeline\stage_01_data_ingestion.py", line 13, in main
    data_ingestion.download_file()
  File "C:\Users\USER\Documents\Text-Summarizer-NLP-Project\src\textSummarizer\components\data_ingestion.py", line 21, in download_file
    logger.info(f"File already exists of size: {self.get_size(Path(self.config.local_data_file))}")
                                                ^^^^^^^^^^^^^
AttributeError: 'DataIngestion' object has no attribute 'get_size'
[2024-06-05 21:20:11,736 - INFO - main: >>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-05 21:20:11,738 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-05 21:20:11,739 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-05 21:20:11,739 - INFO - common: created directory at: artifacts]
[2024-06-05 21:20:11,740 - INFO - common: created directory at: artifacts/data_ingestion]
[2024-06-05 21:20:24,965 - INFO - data_ingestion: artifacts/data_ingestion/data.zip downloaded with the following info: 
Connection: close
Content-Length: 7903594
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "dbc016a060da18070593b83afff580c9b300f0b6ea4147a7988433e04df246ca"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: C710:1507FC:1DACED:2352CC:66607328
Accept-Ranges: bytes
Date: Wed, 05 Jun 2024 14:20:11 GMT
Via: 1.1 varnish
X-Served-By: cache-qpg120087-QPG
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1717597212.516109,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: dfdf8fbf8e44174cc9865e1b2e23671a84a52f42
Expires: Wed, 05 Jun 2024 14:25:11 GMT
Source-Age: 242

]
[2024-06-05 21:20:25,133 - INFO - main: >>>>> stage Data Ingestion stage completed <<<<<<

x=========x]
[2024-06-05 21:20:25,133 - INFO - main: >>>>> stage Data validation stage started <<<<<<]
[2024-06-05 21:20:25,136 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-05 21:20:25,136 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-05 21:20:25,137 - INFO - common: created directory at: artifacts]
[2024-06-05 21:20:25,138 - INFO - common: created directory at: artifacts/data_validation]
[2024-06-05 21:20:25,139 - INFO - main: >>>>> stage Data validation stage completed <<<<<<

x=========x]
[2024-06-06 11:51:10,007 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-06 11:51:10,018 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-06 11:51:10,021 - INFO - common: created directory at: artifacts]
[2024-06-06 11:51:10,021 - INFO - common: created directory at: artifacts/data_transformation]
[2024-06-06 11:51:39,733 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-06 11:51:39,736 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-06 11:51:39,737 - INFO - common: created directory at: artifacts]
[2024-06-06 11:51:39,738 - INFO - common: created directory at: artifacts/data_transformation]
[2024-06-06 11:53:00,910 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-06 11:53:00,913 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-06 11:53:00,916 - INFO - common: created directory at: artifacts]
[2024-06-06 11:53:00,917 - INFO - common: created directory at: artifacts/data_transformation]
[2024-06-06 12:01:59,499 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-06 12:01:59,499 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-06 12:01:59,499 - INFO - common: created directory at: artifacts]
[2024-06-06 12:01:59,499 - INFO - common: created directory at: artifacts/data_transformation]
[2024-06-06 12:03:18,170 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-06 12:03:18,186 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-06 12:03:18,186 - INFO - common: created directory at: artifacts]
[2024-06-06 12:03:18,186 - INFO - common: created directory at: artifacts/data_transformation]
[2024-06-06 12:03:40,365 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-06 12:03:40,367 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-06 12:03:40,369 - INFO - common: created directory at: artifacts]
[2024-06-06 12:03:40,370 - INFO - common: created directory at: artifacts/data_transformation]
[2024-06-06 13:01:50,627 - INFO - main: >>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-06 13:01:50,643 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-06 13:01:50,643 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-06 13:01:50,643 - INFO - common: created directory at: artifacts]
[2024-06-06 13:01:50,643 - INFO - common: created directory at: artifacts/data_ingestion]
[2024-06-06 13:02:01,900 - ERROR - main: <urlopen error [Errno 11001] getaddrinfo failed>]
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1294, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1340, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1289, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1048, in _send_output
    self.send(msg)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 986, in send
    self.connect()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1459, in connect
    super().connect()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 952, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 827, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\USER\Documents\Text-Summarizer-NLP-Project\main.py", line 10, in <module>
    data_ingestion.main()
  File "c:\Users\USER\Documents\Text-Summarizer-NLP-Project\src\textSummarizer\pipeline\stage_01_data_ingestion.py", line 13, in main
    data_ingestion.download_file()
  File "C:\Users\USER\Documents\Text-Summarizer-NLP-Project\src\textSummarizer\components\data_ingestion.py", line 15, in download_file
    filename, headers = request.urlretrieve(
                        ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>
[2024-06-06 13:11:24,130 - INFO - main: >>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-06 13:11:24,146 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-06 13:11:24,146 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-06 13:11:24,146 - INFO - common: created directory at: artifacts]
[2024-06-06 13:11:24,146 - INFO - common: created directory at: artifacts/data_ingestion]
[2024-06-06 13:11:28,631 - INFO - data_ingestion: artifacts/data_ingestion/data.zip downloaded with the following info: 
Connection: close
Content-Length: 7903594
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "dbc016a060da18070593b83afff580c9b300f0b6ea4147a7988433e04df246ca"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 7B64:151E08:2A3E5D:32C788:6661530D
Accept-Ranges: bytes
Date: Thu, 06 Jun 2024 06:11:26 GMT
Via: 1.1 varnish
X-Served-By: cache-qpg1276-QPG
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1717654286.858085,VS0,VE945
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 4f846e6f1f04775667841c2199e8a4b5d4064d4e
Expires: Thu, 06 Jun 2024 06:16:26 GMT
Source-Age: 1

]
[2024-06-06 13:11:29,078 - INFO - main: >>>>> stage Data Ingestion stage completed <<<<<<

x=========x]
[2024-06-06 13:11:29,078 - INFO - main: >>>>> stage Data validation stage started <<<<<<]
[2024-06-06 13:11:29,097 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-06 13:11:29,097 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-06 13:11:29,097 - INFO - common: created directory at: artifacts]
[2024-06-06 13:11:29,103 - INFO - common: created directory at: artifacts/data_validation]
[2024-06-06 13:11:29,107 - INFO - main: >>>>> stage Data validation stage completed <<<<<<

x=========x]
[2024-06-06 13:11:29,107 - INFO - main: >>>>> stage Data transformation stage started <<<<<<]
[2024-06-06 13:11:29,111 - INFO - common: yaml file: Config\config.yaml loaded successfully]
[2024-06-06 13:11:29,119 - INFO - common: yaml file: params.yaml loaded successfully]
[2024-06-06 13:11:29,123 - INFO - common: created directory at: artifacts]
[2024-06-06 13:11:29,123 - INFO - common: created directory at: artifacts/data_transformation]
[2024-06-06 13:11:43,239 - INFO - main: >>>>> stage Data transformation stage completed <<<<<<

x=========x]
